VALUES ('Rachel', 'Carlson', 14, null),
    ('Michael', 'Johnson', 3, 1),    
    ('John', 'Doe', 1, 2),
    ('Jane', 'Smith', 2, 2),
    ('Emily', 'Williams', 4, 1),
    ('Christopher', 'Brown', 5, 5),
    ('Daniel', 'Garcia', 7, 1),
    ('Amanda', 'Jones', 6, 7),
    ('Jennifer', 'Young', 10, 1),
    ('Sarah', 'Martinez', 8, 9),
    ('David', 'Hernandez', 9, 9),
    ('Cara', 'Walker', 13, 1),
    ('Matthew', 'King', 11, 12),
    ('Laura', 'Lee', 12, 12),
    ('Olivia', 'Perez', 11, 12),
    ('William', 'Scott', 11, 12),
    ('Jessica', 'Green', 11, 16),
    ('Ryan', 'Adams', 11, 16);